#pragma once

#define DRAW_AREA_BOX_X1
#define DRAW_AREA_BOX_Y1
#define DRAW_AREA_BOX_X2
#define DRAW_AREA_BOX_Y2

#define DRAW_AREA_X1
#define DRAW_AREA_Y1
#define DRAW_AREA_X2
#define DRAW_AREA_Y2

#define STATUS_AREA_BOX_X1
#define STATUS_AREA_BOX_Y1
#define STATUS_AREA_BOX_X2
#define STATUS_AREA_BOX_Y2

#define CATEGORY_TEXT_X
#define CATEGORY_TEXT_Y
#define CATEGORY_VALUE_X
#define CATEGORY_VALUE_Y

#define SIZE_VALUE_X
#define SIZE_VALUE_Y

#define PROGRESS_TEXT_X
#define PROGRESS_TEXT_Y
#define PROGRESS_VALUE_X
#define PROGRESS_VALUE_Y

#define MISTAKES_TEXT_X      6
#define MISTAKES_TEXT_Y     23
#define MISTAKES_VALUE_X    16    
#define MISTAKES_VALUE_Y    23

#define TIME_TEXT_X         23
#define TIME_TEXT_Y         23
#define TIME_VALUE_X        29
#define TIME_VALUE_Y        23

#define LEGEND_AREA_BOX_X1  47
#define LEGEND_AREA_BOX_Y1   3
#define LEGEND_AREA_BOX_X2  76
#define LEGEND_AREA_BOX_Y2  20

#define LEGEND_COLS_X       48
#define LEGEND_COLS_Y        4
#define LEGEND_NUM_COLS      4
#define LEGEND_NUM_ROWS     16
#define LEGEND_COL_WIDTH     7

#define BUTTON_AREA_BOX_X1  47
#define BUTTON_AREA_BOX_Y1  20
#define BUTTON_AREA_BOX_X2  76
#define BUTTON_AREA_BOX_Y2  24

#define SAVE_TEXT_X         49
#define SAVE_TEXT_Y         21
#define LOAD_TEXT_X         49
#define LOAD_TEXT_Y         23
#define MARK_TEXT_X         59
#define MARK_TEXT_Y         21
#define MAP_TEXT_X          59
#define MAP_TEXT_Y          23
#define OPTS_TEXT_X         68
#define OPTS_TEXT_Y         21
#define EXIT_TEXT_X         68
#define EXTI_TEXT_Y         23

