/* Copyright 2024 Shaun Brandt
   
   Permission is hereby granted, free of charge, to any person obtaining a 
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
   DEALINGS IN THE SOFTWARE.
 */
#pragma once

#define SW_VERSION  "v0.04 (05/22/2024)"

#define LOAD_SCREEN_MAX_LIST_ROWS     19

#define DRAW_VISIBLE_WIDTH  16
#define DRAW_VISIBLE_HEIGHT 16

#define LOAD_COLLECTIONS_TEXT_X     5
#define LOAD_COLLECTIONS_TEXT_Y     3
#define LOAD_PICTURES_TEXT_X       29
#define LOAD_PICTURES_TEXT_Y        3

#define DRAW_AREA_BOX_X1     4
#define DRAW_AREA_BOX_Y1     2
#define DRAW_AREA_BOX_X2    37
#define DRAW_AREA_BOX_Y2    19

#define DRAW_AREA_X1         5
#define DRAW_AREA_Y1         3
#define DRAW_AREA_X2        36
#define DRAW_AREA_Y2        18

#define CURSOR_LOC_X        27
#define CURSOR_LOC_Y         2

#define STATUS_AREA_BOX_X1   4
#define STATUS_AREA_BOX_Y1  19
#define STATUS_AREA_BOX_X2  37
#define STATUS_AREA_BOX_Y2  23

#define STATUS_AREA_X1       5
#define STATUS_AREA_Y1      20
#define STATUS_AREA_X2      36
#define STATUS_AREA_Y2      22

#define CATEGORY_TEXT_X      5
#define CATEGORY_TEXT_Y     20
#define CATEGORY_VALUE_X    15
#define CATEGORY_VALUE_Y    20

#define SIZE_VALUE_X        27
#define SIZE_VALUE_Y        20

#define PROGRESS_TEXT_X      5
#define PROGRESS_TEXT_Y     21
#define PROGRESS_VALUE_X    15
#define PROGRESS_VALUE_Y    21

#define MISTAKES_TEXT_X      5
#define MISTAKES_TEXT_Y     22
#define MISTAKES_VALUE_X    15    
#define MISTAKES_VALUE_Y    22

#define TIME_TEXT_X         22
#define TIME_TEXT_Y         22
#define TIME_VALUE_X        28
#define TIME_VALUE_Y        22

#define LEGEND_AREA_BOX_X1  46
#define LEGEND_AREA_BOX_Y1   2
#define LEGEND_AREA_BOX_X2  75
#define LEGEND_AREA_BOX_Y2  19

#define LEGEND_AREA_X1      47
#define LEGEND_AREA_Y1       3
#define LEGEND_AREA_X2      74
#define LEGEND_AREA_Y2      18

#define LEGEND_TEXT_X       57
#define LEGEND_TEXT_Y        2

#define LEGEND_COLS_X       48
#define LEGEND_CURSOR_X     47
#define LEGEND_COLS_Y        3
#define LEGEND_NUM_COLS      4
#define LEGEND_NUM_ROWS     16
#define LEGEND_COL_WIDTH     7

#define BUTTON_AREA_BOX_X1  46
#define BUTTON_AREA_BOX_Y1  19
#define BUTTON_AREA_BOX_X2  75
#define BUTTON_AREA_BOX_Y2  23

#define BUTTON_AREA_X1      47
#define BUTTON_AREA_Y1      20
#define BUTTON_AREA_X2      74
#define BUTTON_AREA_Y2      22

#define BUTTON_AREA_HLINE_X     46
#define BUTTON_AREA_HLINE_Y     21
#define BUTTON_AREA_HLINE_LEN   30
#define BUTTON_AREA_VLINE1_X    56
#define BUTTON_AREA_VLINE1_Y    19
#define BUTTON_AREA_VLINE1_LEN   5
#define BUTTON_AREA_VLINE2_X    65
#define BUTTON_AREA_VLINE2_Y    19
#define BUTTON_AREA_VLINE2_LEN   5

#define OPTIONS_DIALOG_X1       13
#define OPTIONS_DIALOG_Y1        7
#define OPTIONS_DIALOG_X2       65
#define OPTIONS_DIALOG_Y2       16
#define OPTIONS_HEADER_X        35
#define OPTIONS_HEADER_Y         7
#define OPTION_TEXT_HIGH_RES_X  15
#define OPTION_TEXT_HIGH_RES_Y   9
#define OPTION_TEXT_MARK_X      15
#define OPTION_TEXT_MARK_Y      10
#define OPTION_TEXT_AUTOSAVE_X  15
#define OPTION_TEXT_AUTOSAVE_Y  11
#define OPTION_TEXT_SOUND_X     15
#define OPTION_TEXT_SOUND_Y     12
#define OPTION_HIGH_RES_X       16
#define OPTION_HIGH_RES_Y        9
#define OPTION_MARK_X           16
#define OPTION_MARK_Y           10
#define OPTION_AUTOSAVE_X       16
#define OPTION_AUTOSAVE_Y       11
#define OPTION_SOUND_X          16
#define OPTION_SOUND_Y          12
#define OPTION_SAVE_X           24
#define OPTION_SAVE_Y           14
#define OPTION_CANCEL_X         43
#define OPTION_CANCEL_Y         14

#define SAVE_TEXT_X         48
#define SAVE_TEXT_Y         20
#define LOAD_TEXT_X         48
#define LOAD_TEXT_Y         22
#define MARK_TEXT_X         57
#define MARK_TEXT_Y         20
#define MAP_TEXT_X          58
#define MAP_TEXT_Y          22
#define OPTS_TEXT_X         67
#define OPTS_TEXT_Y         20
#define EXIT_TEXT_X         67
#define EXIT_TEXT_Y         22

